CREATE DATABASE DB_BANCO


CREATE TABLE CUENTA_CORRIENTE(
ID_CLIENTE SERIAL NOT NULL,
NOMBRE_CLIENTE VARCHAR(30) NOT NULL,
MONTO NUMERIC NOT NULL,
CONSTRAINT PK_CUENTA_CORRIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE CUENTA_AHORROS(
ID_CLIENTE SERIAL NOT NULL,
NOMBRE_CLIENTE VARCHAR(30) NOT NULL,
MONTO NUMERIC NOT NULL,
CONSTRAINT PK_CUENTA_AHORROS PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE BITACORA(
ID_BITACORA SERIAL NOT NULL,
TIEMPO TIME WITH TIME ZONE,
DESCRIPCION VARCHAR(150),
CONSTRAINT PK_LOG PRIMARY KEY (ID_BITACORA)
);


CREATE OR REPLACE FUNCTION TRANSACCION () RETURNS TRIGGER 
AS
$$

DECLARE 
	NOMBRE_TABLA VARCHAR(20);
BEGIN
	NOMBRE_TABLA := TG_TABLE_NAME;
	
	RAISE NOTICE 'TRIGGER LLAMADO EN % ANTES DE UN %', TG_TABLE_NAME, TG_OP;

	IF (TG_OP = 'INSERT') THEN
		INSERT INTO BITACORA (TIEMPO, DESCRIPCION)
		VALUES (NOW(),'NUEVO CLIENTE AGREGADO TABLA: '|| NOMBRE_TABLA);
		RETURN NEW;
	END IF;

	IF (TG_OP = 'UPDATE') THEN
		IF (NEW.MONTO < 0)THEN
			RAISE NOTICE 'MONTO INVALIDO, NO SE ACEPTAN NEGATIVOS';
		END IF;
		IF (NEW.MONTO != OLD.MONTO)THEN
			INSERT INTO BITACORA (TIEMPO, DESCRIPCION)
			VALUES (NOW(),'MONTO DE LA CUENTA ACTUALIZADO TABLA: '|| NOMBRE_TABLA ||' '
			||'CLIENTE: '||OLD.NOMBRE_CLIENTE ||'MONTO ANTERIOR: '||OLD.MONTO||'MONTO NUEVO: ' ||NEW.MONTO);
			RETURN NEW;
		END IF;		
	END IF;

	IF (TG_OP = 'DELETE') THEN
		INSERT INTO BITACORA (TIEMPO, DESCRIPCION)
		VALUES (NOW(),'CLIENTE ELIMINADO TABLA: '|| NOMBRE_TABLA ||OLD.NOMBRE_CLIENTE);
		RETURN OLD;
	END IF;
END
$$
LANGUAGE 'plpgsql'


CREATE TRIGGER TR_CUENTA_CORRIENTE
BEFORE INSERT OR UPDATE OR DELETE 
ON CUENTA_CORRIENTE
FOR EACH ROW
EXECUTE PROCEDURE TRANSACCION();

CREATE TRIGGER TR_CUENTA_AHORROS
BEFORE INSERT OR UPDATE OR DELETE 
ON CUENTA_AHORROS
FOR EACH ROW
EXECUTE PROCEDURE TRANSACCION();

--Prueba 1
INSERT INTO CUENTA_AHORROS VALUES ('1','MARIA JOSE SALAS', 1000);
INSERT INTO CUENTA_CORRIENTE VALUES ('1','DIEGO MADRIGAL ARAYA', 2000);

--Prueba 2
DELETE FROM CUENTA_AHORROS WHERE ID_CLIENTE = 1;

--Prueba 3
UPDATE CUENTA_CORRIENTE SET MONTO = 3000 WHERE ID_CLIENTE = 1;

SELECT * FROM CUENTA_AHORROS;
SELECT * FROM CUENTA_CORRIENTE;
SELECT * FROM BITACORA;



